### PR TITLE
Added System Media Player Integration

### PR DESCRIPTION
**Pull request by wapacro**
Hey @pascalopitz 

Thank you for this awesome Sonos Controller for Linux! I only recently started using it myself on a daily basis and one thing that has long bothered me about the official Windows Sonos controller was the lack of integration into the operating system, so without further ado I wanted to take the chance and make this possible at least on Linux :wink: 

Therefore, this pull request adds an MPRIS integration for the currently played song in the currently selected device/group. This allows among other things:

- Showing the currently played song/artist on operating system level (e.g. notification center, taskbar, ...)
- Basic control via the integration just mentioned (play, pause, next, previous)
- Allows the use of media keys on the keyboard without having to have the Sonos controller window focused (as requested here: #74)

Here's how that could look like:
image

Never worked with Electron and only indirectly with React, so very interested in your feedback and please let me know if you want me to adjust anything.

### CODE REVIEW

**Comment by pascalopitz** [comment]
@wapacro This is excellent work!

**Comment by pascalopitz** [comment]
Testing it quickly, I can see that if there's no Song in the queue, I get "Unkown Artist", "Unknown" song.

**Comment by pascalopitz** [comment]
One more thought here: Streams might disable seek, next and so on. I can see from the mpris-service documentation, that there are properties for that available also. They should probably get mapped depending on the current track type.

**Comment by wapacro** [comment]
Many thanks for the inputs :slightly_smiling_face: 

> Testing it quickly, I can see that if there's no Song in the queue, I get "Unknown Artist", "Unknown song".

Indeed, missed that. Unfortunately, I can't find a way right now to close an MPRIS channel/player once it has been instantiated, but I have nevertheless delayed the initialization so that the player is not created until there is effectively something to display. Switching back and forth between devices with and without queue therefore still leads to the "Unknown song" problem; however, it no longer occurs at app startup if the automatically/initially selected device has no queue. See commit 0fb35be

> One more thought here: Streams might disable seek, next and so on. I can see from the mpris-service documentation, that there are properties for that available also. They should probably get mapped depending on the current track type.

Great idea! The anyway (for now) not supported features like seeking are now statically disabled (cfbce46); "play", "next" and "previous" are dynamically de-/activated (15d5f14).

**Comment by pascalopitz** [comment]
New release published, v0.2.9

**Pull request merged**
